#
# file:		test_pull_to_master.yml
#

name: test_pull_to_master
on:
    pull_request:
        branches: [ master ]

jobs:

    # matrix for debian linuxes (for now ubuntu-18.04 and ubuntu-20.04)
    debian-linuxes:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-18.04, ubuntu-20.04]
        steps:
            - uses: actions/checkout@v2
           
            - name: Preparing 3rd party libraries for ${{ matrix.os }}
              run: ./scripts/.cicd/unix_prebuild.sh

            - name: Compiling for ${{ matrix.os }}
              run: ./scripts/.cicd/unix_test_pull_to_master_build.sh
              #working-directory: blabla

            - name: running unittest for ${{ matrix.os }}
              run: ./scripts/.cicd/unix_test_pull_to_master_unittest.sh
            
    # This is for windows
    windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Setup developer command prompt
              uses: ilammy/msvc-dev-cmd@v1

            - name: Preparing 3rd party libraries for windows
              run: echo "will be implemented"

            - name: Compiling for windows
              run: .\scripts\.cicd\windows_test_pull_to_master_build.bat
              #working-directory: blabla

            - name: running unittest for windows
              run: echo "will be implemented"

    # do we need mac ?
    mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Preparing 3rd party libraries for mac
              run: echo "will be implemented"

            - name: Compiling for mac
              run: echo "will be implemented"
              #working-directory: blabla

            - name: running unittest for mac
              run: echo "will be implemented"
